sudo: false
language: node_js
node_js:
  - "4.1"

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - make deps
script:
  - make site

env:
  global:
  - secure: sdFBbpRKNdgSdf+1WWl5U6CiYj1dTvj9AcCKnFJPYrf78LvvdTqzUx/oS2lfziewmAJfk+tkBPIPC8qYbCGjayETM0y/Hpq8acERqPLW/1IjDf2F5yitm+aJ4yKV7IW+foPeJF83HmGFnQbbZMkgvuIp550YyQPBAO3GN9oS3Hvlwc8excQaBUJCd55BQj5XV4/Fh926FMuN6kyYnl9C6tD7YbuWiabGXaqO9rJqxNAfBQ4PA9g1FEycAkfs3T4Q0uR1lRdfF4A6oswt2/AxI+dhzVajCrYVaG/xhyAlr1orSQ+AQgGM5sqxGVztAcn6bvzXLDk+Fe9NgCP6Zt3bPAQBtCFg5xV12wg64N1p278v06/5uw2heahTa5kqLr7Q64CjgbLfuUJaumS1oYgVf/f9Ftad/3mvbuV/FdT4LqFq8YOMjrN5liFy6LTh7GUO6qxrmGVxOTJd7T7dyv8qofteNknyI0INBVa70c3Zjr47XBdPtIvjUDy9wyHJYL3Vz5apoaxC2FqJ2ECT5B/j7p8RNe2GFdJay59D/mX2Yez5JrTjeVbfOmm1Hnc6Yy9yVYVx5k/rijKCzK4djcSpRrVBzkAwD2JsRijbPypVaHtddPBv9kIsuYFYsOrEkNdckdJ7SXmU9VDWjNLA1SfsMLWhvg7ygdDdPjUlI4g/CZ4=
  - secure: WdEAnHpDJhQBidNdRTN4kOl7W9hrut5ds2ZOLHEpiAngTKxR8sQGgkVS+AGNH0C2/R8o4wNe53Ig5QW/f+lBR7xXX7D3BDHAhLW4eeZTAeORX35P/fdkVZT5xBymR+0LCSxdWHlK6ltPLAjc4BoRd+25DIVmagNHMLZpVFtO0WuzY/YJ2UlG9/2TFRNZLIlfCBJ8yaojtGCk4CkNKffPZiAoQ+gGRi9QvANsvKdmxKSMwIdqjggFp2rOwCyoHAi6/fpj/NdA308BRNdXcroY0Y7LZySVtOC9JEwehyMXW86pW2+iD4U0Od+sW5NjxdO+T20qWnUaWRgCSThwcwVPMPhJ7dHi05+imidUC6g4oJ00ZG3wzlWOoyYT1yQj3YWMsaPleZLVSnS8hfAV8pO0kJQq4bGvc/abVteH/6RbV463amvgoZt5RIHbDloiIJsZH/DkB7UbgcJDr48+wP83x/XylHhCzz0ggx43/1Nc6UZt3f7JZqCxVkiR3BXtBsa1NHrGVqvGLd4vCbxhYG9WkjCDO/fEaHW16qsL/ZrOWslYSl4b5hxdrLbDO5iN7lRQ3wD/ZJcIbyq6Y5vazeMq7Rq5nsJKFanrM2Xg91khjfpUiXeVbygqqKKU3l8XgyNVm2fEKXLJ8M8Pd06E4lEog4knAfgXCi72uza1n+a2LQQ=

after_success:
  - if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" == "master" ];  then make prod; fi
