sudo: false
language: node_js
node_js:
  - '4.1'

before_install:
  - pip install --user awscli
  - export PATH=$PATH:$HOME/.local/bin

install:
  - make deps
script:
  - make site

env:
  global:
    - secure: XMMVAfww7+MIGiU9lDjOSWVE0tna9H4+iWu0/DqSFp964arxHgLYlBNFggvPNKWGoZgIKjGsTLbSOJfj8wbiOsvo7FSg4PkWsG9ZY6jkgwi4mPgeP0d2LeMmg4JA/TRB8Zmg5Ri306G91JvrJQ7H1BDRSUysFoLnADBay9mx1FuZEJnEvOxLC4SmsA7DKnWnMo6iw9UFpAf6xxOqlhQAWjRI7A0Momy6cjXneas2sCYjIreL60vtv7VGdH0j+nxWGumSh1+8aVc7Jkkx80Al2PHpqjUt3HNP3c0Fjfba1EGEtqJD1U7ZAokVy6VQk6duZ9WmcusNkOUnLUs3FwjO5ZYZlddW2bPTs48zqCjj37Oaw3lwQ9bn1TolhprzPdK0He5QwA2MoswmnJ0VpyYDNeGm3gcV6IrBS9wSxvvmxel+jqGINAlCvtf6R03UT08we6/1EJ27AUOx8xFwaIufUI+DPqvPrB7L8LPmIRl99bqSsuVc1AbZoODhTdRaTWIMuDfHesE/X5aEZ7weagOqsPzRNTklidveAVoMRIcWlJa7qhX1dedNQdMK6rYO6dd1dwK6JXBVhOyVUFLYw0yga0Nk+Z3xxGu4RuR3lMMoKC876VqEzW+cPH/LV3hnO4rqykvsGStwLWxa4rCwj/Q71+XJaTGzfXIIm4vepNLJRf4=
    - secure: bxAhim5k8PLb34I5IN8GFS3ljqirmRow8LeWWGrFtnVCpnL74w2vG4hFeoUmN+A2GwXXewVpNEJPGxRXYMFK6QUlGETew/a9TwPEnQ5Xit/sadtSgq7nj3UDb4ZxATFLer1cJEzZhStV+8FdNk7ORH1to5G0glaNsxhiaZvrXxkQxKLGAUVhAODfM+iJDsCVrSV6RSK9kfuShxKT8j/NYv7y4NoRwZQB92m9gZhSPnf2Xm1AuDwFHL0P4Htw6d/3YClhHZQWWPFV0d/AvQ8s3OuJreMTDal7cao+DEBI1fUQ55N3oBl8ODNfH0xTh51Ze8+RszYRg1HzbOPbOnARKRFtyXwimaEByZlb+fF19xHN7APtBXKAuV+nnpw2N1eEz8UyWooOxGB6dDSdIv+XdsZ4le8wGx0t+z+wtJaHjmgLg/FbBG3FBUvmYxzdCzD2SIPRQbQ96SQm3wS49O4nGfi+NUXX+movLkl48hJqhihuviXuQHk08/yYikrH3sxP++NXPIF5blTKxqy7VyJ/YxTcCqdRuuR0XgIH+Phk5tY1jw3jWjQyTyiaKFA/txPdpHi8MUeM2o8QI1ZgNhjDUwinc83O8UQ+CPTwrB4kKEZk3mkK+u13OFH/X99NvdMtE0eJ7i1DGCIdeqLVXXb4yWbDJERoow47EwNiM2iQBqY=

after_success:
  - if [ "$TRAVIS_REPO_SLUG" == "andrewkroh/beat-insights" ] && [ "$TRAVIS_BRANCH" == "master" ]; then make prod; fi
